require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/supports", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Support. As you add validations to Support, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Support.create! valid_attributes
      get supports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      support = Support.create! valid_attributes
      get support_url(support)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_support_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      support = Support.create! valid_attributes
      get edit_support_url(support)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Support" do
        expect {
          post supports_url, params: { support: valid_attributes }
        }.to change(Support, :count).by(1)
      end

      it "redirects to the created support" do
        post supports_url, params: { support: valid_attributes }
        expect(response).to redirect_to(support_url(Support.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Support" do
        expect {
          post supports_url, params: { support: invalid_attributes }
        }.to change(Support, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post supports_url, params: { support: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested support" do
        support = Support.create! valid_attributes
        patch support_url(support), params: { support: new_attributes }
        support.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the support" do
        support = Support.create! valid_attributes
        patch support_url(support), params: { support: new_attributes }
        support.reload
        expect(response).to redirect_to(support_url(support))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        support = Support.create! valid_attributes
        patch support_url(support), params: { support: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested support" do
      support = Support.create! valid_attributes
      expect {
        delete support_url(support)
      }.to change(Support, :count).by(-1)
    end

    it "redirects to the supports list" do
      support = Support.create! valid_attributes
      delete support_url(support)
      expect(response).to redirect_to(supports_url)
    end
  end
end
